# Generated by Django 5.2.4 on 2025-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='author',
            field=models.CharField(blank=True, help_text='Author name', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_by',
            field=models.CharField(blank=True, help_text='Uploader name', max_length=100),
        ),
    ]
