# Generated by Django 5.2.4 on 2025-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinrecord',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='checkinrecord',
            name='location',
        ),
        migrations.RemoveField(
            model_name='checkinrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='company',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='reason',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkinrecord',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterModelTable(
            name='checkinrecord',
            table='staff_checkinrecord',
        ),
    ]
