# Generated by Django 5.2.6 on 2025-09-12 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('spotlights_ytd', models.IntegerField(default=0)),
                ('spotlights_mtd', models.IntegerField(default=0)),
                ('safety_tour_ytd', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('safety_tour_mtd', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('possession_average', models.IntegerField(default=0)),
                ('average_work_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('in_process_critical', models.IntegerField(default=0)),
                ('in_process_warning', models.IntegerField(default=0)),
                ('possession_active', models.IntegerField(default=0)),
                ('possession_inactive', models.IntegerField(default=0)),
                ('preparation_status', models.IntegerField(default=0)),
                ('breakdown_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StaffLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_in_depot', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('spotlights', 'Spotlight Reports'), ('safety_tours', 'Safety Tours'), ('possession_utilization', 'Possession Utilization'), ('in_process_status', 'In Process Status'), ('preparation_status', 'Preparation Status')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('metric_type', 'name', 'date')},
            },
        ),
    ]
