# Generated by Django 5.2.4 on 2025-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafflocation',
            name='user',
        ),
        migrations.AddField(
            model_name='stafflocation',
            name='user_name',
            field=models.CharField(default='Unknown', help_text='Staff member name', max_length=100),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='created_by',
            field=models.CharField(blank=True, help_text='Name of creator', max_length=100),
        ),
        migrations.AlterField(
            model_name='stafflocation',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
