# Generated by Django 5.2.4 on 2025-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.CharField(blank=True, help_text='Name of uploader', max_length=100),
        ),
    ]
