# Generated by Django 5.2.4 on 2025-09-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visit_reason',
            field=models.CharField(choices=[('employee', 'Employee'), ('visitor', 'Visitor'), ('contractor', 'Contractor'), ('delivery', 'Delivery'), ('other', 'Other')], default='employee', max_length=20),
        ),
    ]
