# Generated by Django 5.2.4 on 2025-09-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_visit_date_customuser_visit_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='visit_reason',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('employee', 'Employee'), ('visitor', 'Visitor'), ('contractor', 'Contractor'), ('delivery', 'Delivery'), ('other', 'Other')], default='customer', max_length=20),
        ),
    ]
